apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cmh1448/finvibe-monolith:bdccc60
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: redis-password
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: mongo-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finvibe-jwt-secret
                  key: secret
            - name: KIS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-api-key
            - name: KIS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-api-secret
            - name: KIS_USER_ID
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-user-id
            - name: KIS_API_KEY_2
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-api-key2
            - name: KIS_API_SECRET_2
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-api-secret2
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: gemini-api-key

            # [일반 설정]
            - name: DB_URL
              value: "jdbc:mariadb://mariadb-external:3306/finvibe"
            - name: REDIS_HOST
              value: "redis-external"
            - name: REDIS_MODE
              value: "cluster"
            - name: REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.finvibe.svc.cluster.local:6379"
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.finvibe.svc.cluster.local:6379"
            - name: SPRING_REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.finvibe.svc.cluster.local:6379"
            - name: MARKET_REDIS_PUBSUB_CURRENT_PRICE_UPDATED_PARTITION_COUNT
              value: "3"
            - name: MARKET_REDIS_PUBSUB_CURRENT_PRICE_UPDATED_MODE
              value: "sharded"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-external:9092"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          ports:
            - containerPort: 8080
