apiVersion: v1
kind: Service
metadata:
  name: backend-batch
  labels:
    monitoring: enabled
spec:
  selector:
    app: backend-batch
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
