apiVersion: apps/v1
kind: Deployment
metadata:
  name: profit-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profit-worker
  template:
    metadata:
      labels:
        app: profit-worker
    spec:
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: profit-worker
          image: cmh1448/finvibe-profit-worker:a333846
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: redis-password

            # [일반 설정]
            - name: DB_URL
              value: "jdbc:mariadb://mariadb-external:3306/finvibe"
            - name: REDIS_HOST
              value: "redis-external"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_MODE
              value: "cluster"
            - name: REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.finvibe.svc.cluster.local:6379"
            - name: SPRING_DATA_REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.finvibe.svc.cluster.local:6379"
            - name: SPRING_REDIS_CLUSTER_NODES
              value: "redis-cluster-0.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.finvibe.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.finvibe.svc.cluster.local:6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-external:9092"
            - name: APP_PROFIT_RECALCULATION_PARALLELISM
              value: "32"
            - name: APP_PROFIT_RECALCULATION_QUEUE_CAPACITY
              value: "4096"

          resources:
            requests:
              cpu: "300m"
              memory: "768Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          ports:
            - containerPort: 8080
