apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment
  template:
    metadata:
      labels:
        app: investment
    spec:
      containers:
        - name: investment
          image: 51taek/finvibe-investment:16c10ff
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: redis-password
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: mongo-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finvibe-jwt-secret
                  key: secret
            - name: KIS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-api-key
            - name: KIS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-api-secret
            - name: KIS_USER_ID
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: kis-user-id

            # [일반 설정]
            - name: DB_URL
              value: "jdbc:mariadb://mariadb-external:3306/finvibe"
            - name: REDIS_HOST
              value: "redis-external"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-external:9092"
          ports:
            - containerPort: 8080
