apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment
  template:
    metadata:
      labels:
        app: investment
    spec:
      containers:
        - name: investment
          image: 51taek/finvibe:717cd68
          ports:
            - containerPort: 8080
