apiVersion: v1
kind: Service
metadata:
  name: profit-worker-webflux
  labels:
    monitoring: enabled
spec:
  selector:
    app: profit-worker-webflux
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
