apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: cmh1448/finvibe-user:6ac7cad
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: db-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: redis-password
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: mongo-url
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finvibe-app-secrets
                  key: google-client-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: finvibe-jwt-secret
                  key: secret

            # [일반 설정]
            - name: DB_URL
              value: "jdbc:mariadb://mariadb-external:3306/finvibe"
            - name: REDIS_HOST
              value: "redis-external"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-external:9092"
            - name: GOOGLE_CLIENT_ID
              value: 60942013677-7e0ccida6basbq1o9bg128oe35c2fdu8.apps.googleusercontent.com
            - name: OAUTH_REDIRECT_URL
              value: "https://finvibe.space/oauth/callback"
            - name: OAUTH_BASE_URI
              value: "https://finvibe.space/api/user"
          ports:
            - containerPort: 8080
